Repository YAPP-Github/Eatda-Server, pull requests merged in 2025-08, with the labels that each got.

#138 [Feat] 어플리케이션 로그 파일 백업
  terraform/dev/locals.tf
  terraform/dev/main.tf
  terraform/dev/s3/main.tf
  terraform/dev/s3/scripts/app-backup-dev-logs.sh
  terraform/dev/scripts/user-data.sh
  terraform/prod/main.tf
  terraform/prod/s3/main.tf
  terraform/prod/s3/scripts/app-backup-prod-logs.sh
  terraform/prod/scripts/user-data.sh
Labels: feat

#141 [Fix] prod cronie 설치 추가
  terraform/prod/scripts/user-data.sh
Labels: feat

#143 [Test] StoryControllerTest 가 Mock을 쓰지 않도록 개선
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/fixture/StoryGenerator.java
Labels: test

#144 [Docs] API 명세서 표기 수정
  src/test/java/eatda/document/Tag.java
  src/test/java/eatda/document/store/CheerDocumentTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
Labels: docs

#162 [Hotfix] 임시적으로 응원 최대 개수를 인 당 10,000개까지 허용
  src/main/java/eatda/service/cheer/CheerService.java
  src/test/java/eatda/service/cheer/CheerServiceTest.java
Labels: hotfix

#167 [Feat] '최신 응원 검색 API'의 유저 정보 추가
  src/main/java/eatda/controller/cheer/CheerPreviewResponse.java
  src/main/java/eatda/repository/cheer/CheerRepository.java
  src/main/java/eatda/service/cheer/CheerService.java
  src/main/resources/application.yml
  src/test/java/eatda/document/store/CheerDocumentTest.java
  src/test/resources/application.yml
Labels: feat

#168 [Feat] 자신이 응원한 가게 조회 API 구현
  src/main/java/eatda/controller/store/StoreController.java
  src/main/java/eatda/controller/store/StoreInMemberResponse.java
  src/main/java/eatda/controller/store/StoresInMemberResponse.java
  src/main/java/eatda/repository/cheer/CheerRepository.java
  src/main/java/eatda/repository/store/StoreRepository.java
  src/main/java/eatda/service/store/StoreService.java
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/store/StoreControllerTest.java
  src/test/java/eatda/document/cheer/CheerDocumentTest.java
  src/test/java/eatda/document/store/StoreDocumentTest.java
  src/test/java/eatda/fixture/CheerGenerator.java
  src/test/java/eatda/repository/store/StoreRepositoryTest.java
  src/test/java/eatda/service/store/StoreServiceTest.java
Labels: feat

#172 [Feat] 응원 API 응답에 태그 정보 추가
  src/main/java/eatda/controller/cheer/CheerInStoreResponse.java
  src/main/java/eatda/controller/cheer/CheerPreviewResponse.java
  src/main/java/eatda/repository/cheer/CheerRepository.java
  src/main/java/eatda/service/cheer/CheerService.java
  src/test/java/eatda/controller/cheer/CheerControllerTest.java
  src/test/java/eatda/document/cheer/CheerDocumentTest.java
Labels: feat

#179 [Feat] '최근 응원한 가게 조회 API'에 검색 조건 추가
  src/main/java/eatda/controller/store/StoreController.java
  src/main/java/eatda/controller/store/StoreSearchParameters.java
  src/main/java/eatda/domain/store/SearchDistrict.java
  src/main/java/eatda/domain/store/Store.java
  src/main/java/eatda/repository/store/StoreRepository.java
  src/main/java/eatda/service/store/StoreService.java
  src/test/java/eatda/controller/store/StoreControllerTest.java
  src/test/java/eatda/document/store/StoreDocumentTest.java
  src/test/java/eatda/fixture/StoreGenerator.java
  src/test/java/eatda/repository/BaseRepositoryTest.java
  src/test/java/eatda/repository/store/StoreRepositoryTest.java
  src/test/java/eatda/service/store/StoreServiceTest.java
Labels: feat

#180 [Feat] '최신 응원 조회 API'에 검색 조건 추가
  src/main/java/eatda/controller/cheer/CheerController.java
  src/main/java/eatda/controller/cheer/CheerSearchParameters.java
  src/main/java/eatda/controller/store/SearchDistrict.java
  src/main/java/eatda/repository/cheer/CheerRepository.java
  src/main/java/eatda/repository/store/StoreRepository.java
  src/main/java/eatda/service/cheer/CheerService.java
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/cheer/CheerControllerTest.java
  src/test/java/eatda/document/cheer/CheerDocumentTest.java
  src/test/java/eatda/repository/cheer/CheerRepositoryTest.java
  src/test/java/eatda/service/cheer/CheerServiceTest.java
Labels: feat

#184 [Fix] dev 환경 db 백업 문제 수정
  terraform/common/locals.tf
  terraform/dev/outputs.tf
  terraform/dev/s3/outputs.tf
  terraform/dev/s3/scripts/mysql-backup.sh
  terraform/dev/scripts/user-data.sh
  terraform/prod/outputs.tf
  terraform/prod/rds/outputs.tf
Labels: chore, fix

#192 [Refactor] terraform deprecated 된 명령어인 name을 id로 변경
  terraform/common/locals.tf
Labels: ci
