Repository YAPP-Github/Eatda-Server, pull requests merged in 2025-07, with the labels that each got.

#42 [Chore] Route53과 Vercel 도메인 연동 작업
  terraform/common/locals.tf
  terraform/common/main.tf
  terraform/common/route53/main.tf
  terraform/common/route53/variables.tf
Labels: chore

#35 [Feat] 서비스 회원 가입/로그인 API 구현
  src/main/java/timeeat/client/oauth/OauthMemberInformation.java
  src/main/java/timeeat/controller/auth/AuthController.java
  src/main/java/timeeat/controller/auth/LoginRequest.java
  src/main/java/timeeat/controller/auth/LoginResponse.java
  src/main/java/timeeat/controller/auth/MemberLoginRequest.java
  src/main/java/timeeat/controller/member/MemberController.java
  src/main/java/timeeat/controller/member/MemberResponse.java
  src/main/java/timeeat/controller/member/MemberUpdateRequest.java
  src/main/java/timeeat/controller/web/auth/AuthMemberArgumentResolver.java
  src/main/java/timeeat/domain/member/Member.java
  src/main/java/timeeat/domain/member/MobilePhoneNumber.java
  src/main/java/timeeat/exception/BusinessErrorCode.java
  src/main/java/timeeat/repository/member/MemberRepository.java
  src/main/java/timeeat/service/auth/AuthService.java
  src/main/java/timeeat/service/service/MemberService.java
  src/test/java/timeeat/controller/BaseControllerTest.java
  src/test/java/timeeat/controller/auth/AuthControllerTest.java
  src/test/java/timeeat/controller/member/MemberControllerTest.java
  src/test/java/timeeat/document/BaseDocumentTest.java
  src/test/java/timeeat/document/Tag.java
  src/test/java/timeeat/document/auth/AuthDocumentTest.java
  src/test/java/timeeat/document/member/MemberDocumentTest.java
  src/test/java/timeeat/domain/bookmark/BookmarkTest.java
  src/test/java/timeeat/domain/member/MemberTest.java
  src/test/java/timeeat/domain/member/MobilePhoneNumberTest.java
  src/test/java/timeeat/fixture/MemberGenerator.java
  src/test/java/timeeat/repository/BaseRepositoryTest.java
  src/test/java/timeeat/service/BaseServiceTest.java
  src/test/java/timeeat/service/auth/AuthServiceTest.java
  src/test/java/timeeat/service/service/MemberServiceTest.java
Labels: feat

#39 [Feat] 400/500번대 에러 처리
  build.gradle
  settings.gradle
  src/main/java/timeeat/client/oauth/OauthProperties.java
  src/main/java/timeeat/client/oauth/OauthServerErrorHandler.java
  src/main/java/timeeat/config/CorsConfig.java
  src/main/java/timeeat/controller/web/jwt/JwtProperties.java
  src/main/java/timeeat/exception/BusinessErrorCode.java
  src/main/java/timeeat/exception/BusinessException.java
  src/main/java/timeeat/exception/ErrorResponse.java
  src/main/java/timeeat/exception/EtcErrorCode.java
  src/main/java/timeeat/exception/GlobalExceptionHandler.java
  src/main/java/timeeat/exception/InitializeException.java
  src/test/java/timeeat/controller/web/jwt/JwtPropertiesTest.java
Labels: feat

#43 [Test] 로그인 API 테스트 케이스 추가 및 Rest Docs 문서 수정
  src/main/java/timeeat/controller/auth/AuthController.java
  src/test/java/timeeat/controller/BaseControllerTest.java
  src/test/java/timeeat/controller/auth/AuthControllerTest.java
  src/test/java/timeeat/document/auth/AuthDocumentTest.java
  src/test/java/timeeat/document/member/MemberDocumentTest.java
Labels: test

#48 [Feat] 닉네임, 전화번호 중복 확인 API 구현
  src/main/java/timeeat/controller/member/MemberController.java
  src/main/java/timeeat/exception/EtcErrorCode.java
  src/main/java/timeeat/exception/GlobalExceptionHandler.java
  src/main/java/timeeat/service/service/MemberService.java
  src/test/java/timeeat/controller/BaseControllerTest.java
  src/test/java/timeeat/controller/member/MemberControllerTest.java
  src/test/java/timeeat/document/auth/AuthDocumentTest.java
  src/test/java/timeeat/document/member/MemberDocumentTest.java
  src/test/java/timeeat/fixture/MemberGenerator.java
  src/test/java/timeeat/service/service/MemberServiceTest.java
Labels: feat

#50 [Fix] 요청한 클라이언트의 주소를 Origin 대신 Refer, Body 로 받도록 수정
  src/main/java/timeeat/client/oauth/OauthClient.java
  src/main/java/timeeat/client/oauth/OauthProperties.java
  src/main/java/timeeat/controller/auth/AuthController.java
  src/main/java/timeeat/controller/auth/LoginRequest.java
  src/main/java/timeeat/exception/InitializeException.java
  src/main/java/timeeat/service/auth/AuthService.java
  src/test/java/timeeat/client/oauth/OauthClientTest.java
  src/test/java/timeeat/client/oauth/OauthPropertiesTest.java
  src/test/java/timeeat/controller/auth/AuthControllerTest.java
  src/test/java/timeeat/document/auth/AuthDocumentTest.java
  src/test/java/timeeat/service/auth/AuthServiceTest.java
Labels: fix

#64 [Docs] 에러 응답에 대한 문서화
  src/test/java/eatda/document/BaseDocumentTest.java
  src/test/java/eatda/document/auth/AuthDocumentTest.java
  src/test/java/eatda/document/member/MemberDocumentTest.java
  src/test/java/eatda/document/store/StoreDocumentTest.java
Labels: docs

#72 [Fix] 회원가입 API 에서 이메일을 이용하도록 수정
  src/main/java/eatda/client/oauth/OauthMemberInformation.java
  src/main/java/eatda/client/oauth/OauthMemberInformationDeserializer.java
  src/main/java/eatda/controller/member/MemberResponse.java
  src/main/java/eatda/domain/member/Member.java
  src/main/java/eatda/exception/BusinessErrorCode.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/seed/dev/V2__dev_init_data.sql
  src/main/resources/db/seed/local/V2__local_init_data.sql
  src/test/java/eatda/client/oauth/OauthClientTest.java
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/member/MemberControllerTest.java
  src/test/java/eatda/document/auth/AuthDocumentTest.java
  src/test/java/eatda/document/member/MemberDocumentTest.java
  src/test/java/eatda/domain/bookmark/BookmarkTest.java
  src/test/java/eatda/domain/member/MemberTest.java
  src/test/java/eatda/fixture/MemberGenerator.java
  src/test/java/eatda/service/auth/AuthServiceTest.java
  src/test/java/eatda/service/member/MemberServiceTest.java
Labels: fix

#80 [Feat] 스토리 등록 구현
  src/main/java/eatda/controller/story/FilteredSearchResult.java
  src/main/java/eatda/controller/story/StoriesResponse.java
  src/main/java/eatda/controller/story/StoryController.java
  src/main/java/eatda/controller/story/StoryRegisterRequest.java
  src/main/java/eatda/controller/story/StoryResponse.java
  src/main/java/eatda/domain/story/Story.java
  src/main/java/eatda/exception/BusinessErrorCode.java
  src/main/java/eatda/exception/GlobalExceptionHandler.java
  src/main/java/eatda/repository/story/StoryRepository.java
  src/main/java/eatda/service/common/ImageDomain.java
  src/main/java/eatda/service/common/ImageService.java
  src/main/java/eatda/service/store/StoreService.java
  src/main/java/eatda/service/story/StoryService.java
  src/main/resources/db/migration/V3__add_story_table.sql
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/BaseDocumentTest.java
  src/test/java/eatda/document/Tag.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
  src/test/java/eatda/domain/story/StoryTest.java
  src/test/java/eatda/service/BaseServiceTest.java
  src/test/java/eatda/service/common/ImageServiceTest.java
  src/test/java/eatda/service/story/StoryServiceTest.java
Labels: feat

#84 [Feat] 스토리 목록 조회 구현
  src/main/java/eatda/controller/story/StoryController.java
  src/main/java/eatda/repository/story/StoryRepository.java
  src/main/java/eatda/service/story/StoryService.java
  src/main/resources/db/seed/dev/V4__dev_add_story_data.sql
  src/main/resources/db/seed/local/V4__local_add_story_data.sql
  src/main/resources/db/seed/prod/V4__local_add_story_data.sql
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
  src/test/java/eatda/service/BaseServiceTest.java
  src/test/java/eatda/service/story/StoryServiceTest.java
Labels: feat

#86 [Feat] 가게 조회 API 구현
  src/main/java/eatda/controller/store/StoreController.java
  src/main/java/eatda/controller/store/StorePreviewResponse.java
  src/main/java/eatda/controller/store/StoresResponse.java
  src/main/java/eatda/repository/store/CheerRepository.java
  src/main/java/eatda/repository/store/StoreRepository.java
  src/main/java/eatda/service/store/CheerService.java
  src/main/java/eatda/service/store/StoreService.java
  src/test/java/eatda/controller/store/StoreControllerTest.java
  src/test/java/eatda/document/store/StoreDocumentTest.java
  src/test/java/eatda/fixture/CheerGenerator.java
  src/test/java/eatda/repository/BaseRepositoryTest.java
  src/test/java/eatda/repository/store/CheerRepositoryTest.java
  src/test/java/eatda/service/store/StoreServiceTest.java
Labels: feat

#87 [Feat] 스토리 상세 조회 기능 구현
  .github/workflows/automatic-erd.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/terraform-plan.yml
  src/main/java/eatda/controller/story/FilteredSearchResult.java
  src/main/java/eatda/controller/story/StoryController.java
  src/main/java/eatda/controller/story/StoryResponse.java
  src/main/java/eatda/domain/story/Story.java
  src/main/java/eatda/exception/BusinessErrorCode.java
  src/main/java/eatda/service/story/StoryService.java
  src/main/resources/db/migration/V3__add_story_table.sql
  src/main/resources/db/seed/dev/V2__dev_init_data.sql
  src/main/resources/db/seed/dev/V4__dev_add_story_data.sql
  src/main/resources/db/seed/local/V2__local_init_data.sql
  src/main/resources/db/seed/local/V4__local_add_story_data.sql
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
  src/test/java/eatda/domain/story/StoryTest.java
  src/test/java/eatda/service/story/StoryServiceTest.java
Labels: feat

#94 [Fix] 스토리 등록 로직 수정
  src/main/java/eatda/controller/story/StoryController.java
  src/main/java/eatda/controller/story/StoryRegisterResponse.java
  src/main/java/eatda/service/story/StoryService.java
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
  src/test/java/eatda/service/story/StoryServiceTest.java
Labels: fix

#100 [Fix] dev 초기 데이터 수정
  src/main/resources/db/seed/dev/V2__dev_init_data.sql
  src/main/resources/db/seed/local/V2__local_init_data.sql
  src/main/resources/db/seed/local/V4__local_add_story_data.sql
Labels: fix

#101 [Refactor] 이미지 도메인 객체 도입
  src/main/java/eatda/client/file/FileClient.java
  src/main/java/eatda/domain/Image.java
  src/main/java/eatda/domain/ImageKey.java
  src/main/java/eatda/domain/article/Article.java
  src/main/java/eatda/domain/store/Cheer.java
  src/main/java/eatda/domain/story/Story.java
  src/main/java/eatda/repository/store/CheerRepository.java
  src/main/java/eatda/service/article/ArticleService.java
  src/main/java/eatda/service/store/CheerService.java
  src/main/java/eatda/service/store/StoreService.java
  src/main/java/eatda/service/story/StoryService.java
  src/main/java/eatda/storage/image/CachePreSignedUrlStorage.java
  src/main/java/eatda/storage/image/ExternalImageStorage.java
  src/main/java/eatda/storage/image/ImageStorage.java
  src/test/java/eatda/client/file/FileClientTest.java
  src/test/java/eatda/controller/BaseControllerTest.java
  src/test/java/eatda/controller/store/CheerControllerTest.java
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/store/CheerDocumentTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
  src/test/java/eatda/domain/ImageKeyTest.java
  src/test/java/eatda/domain/ImageTest.java
  src/test/java/eatda/domain/store/CheerTest.java
  src/test/java/eatda/domain/story/StoryTest.java
  src/test/java/eatda/fixture/ArticleGenerator.java
  src/test/java/eatda/fixture/CheerGenerator.java
  src/test/java/eatda/repository/store/CheerRepositoryTest.java
  src/test/java/eatda/service/BaseServiceTest.java
  src/test/java/eatda/service/store/CheerServiceTest.java
  src/test/java/eatda/service/story/StoryServiceTest.java
  src/test/java/eatda/storage/image/CachePreSignedUrlStorageTest.java
  src/test/java/eatda/storage/image/ExternalImageStorageTest.java
  src/test/java/eatda/storage/image/ImageStorageTest.java
Labels: refactor

#114 [Fix] 카테고리 통합 작업 및 메서드 정리
  src/main/java/eatda/client/map/StoreSearchResult.java
  src/main/java/eatda/domain/store/StoreCategory.java
Labels: fix

#109 [Feat] 가게 이미지 조회 API 구현
  src/main/java/eatda/controller/store/ImagesResponse.java
  src/main/java/eatda/controller/store/StoreController.java
  src/main/java/eatda/repository/store/CheerRepository.java
  src/main/java/eatda/service/store/StoreService.java
  src/test/java/eatda/controller/store/StoreControllerTest.java
  src/test/java/eatda/document/store/StoreDocumentTest.java
  src/test/java/eatda/repository/store/CheerRepositoryTest.java
  src/test/java/eatda/service/store/StoreServiceTest.java
Labels: feat

#112 [Test] 생성 시각에 의한 테스트 개선
  src/main/java/eatda/domain/AuditingEntity.java
  src/test/java/eatda/controller/article/ArticleControllerTest.java
  src/test/java/eatda/controller/store/CheerControllerTest.java
  src/test/java/eatda/controller/store/StoreControllerTest.java
  src/test/java/eatda/fixture/ArticleGenerator.java
  src/test/java/eatda/fixture/CheerGenerator.java
  src/test/java/eatda/fixture/StoreGenerator.java
  src/test/java/eatda/service/article/ArticleServiceTest.java
  src/test/java/eatda/service/store/CheerServiceTest.java
  src/test/java/eatda/service/store/StoreServiceTest.java
  src/test/java/eatda/util/DomainUtils.java
Labels: test

#122 [Fix] 스토리 상세 조회 API에 회원 정보 추가
  src/main/java/eatda/controller/story/StoryResponse.java
  src/main/java/eatda/service/story/StoryService.java
  src/test/java/eatda/controller/story/StoryControllerTest.java
  src/test/java/eatda/document/story/StoryDocumentTest.java
Labels: fix
