Repository YAPP-Github/Eatda-Server, pull requests merged in 2025-06, with the labels that each got.

#6 [Ci] 소나 클라우드, 인프라 변경 감지 추가
  .github/pull-request-template.md
  .github/workflows/notify-discord-noti.yml
  .github/workflows/notify-discord-pr.yml
  .github/workflows/sonarcloud.yml
  build.gradle
Labels: ci

#11 chore: jira 이슈 등록 액션 추가
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#16 [Chore] ci 템플릿 수정 및 이슈 타입 수정
  .github/ISSUE_TEMPLATE/08-ci-template.yml
  .github/workflows/create-jira-issue.yml
Labels: chore

#26 [Feat] 카카오 로그인 API 연결
  src/main/java/timeeat/client/oauth/OauthClient.java
  src/main/java/timeeat/client/oauth/OauthMemberInformation.java
  src/main/java/timeeat/client/oauth/OauthMemberInformationDeserializer.java
  src/main/java/timeeat/client/oauth/OauthProperties.java
  src/main/java/timeeat/client/oauth/OauthServerErrorHandler.java
  src/main/java/timeeat/client/oauth/OauthToken.java
  src/main/java/timeeat/controller/member/MemberController.java
  src/main/java/timeeat/controller/member/MemberLoginRequest.java
  src/main/java/timeeat/service/member/MemberService.java
  src/test/java/timeeat/client/oauth/OauthClientTest.java
  src/test/java/timeeat/controller/member/MemberControllerTest.java
  src/test/java/timeeat/document/member/MemberDocumentTest.java
  src/test/resources/application.yml
Labels: feat

#34 [Ci] 기획 변경으로 인한 인프라 변경점 적용
  .github/workflows/close-jira-issue.yml
  CHANGELOG.md
  src/main/resources/application-dev.yml
  terraform-bootstrap/backend.tf
  terraform-bootstrap/main.tf
  terraform-bootstrap/outputs.tf
  terraform/common/alb/locals.tf
  terraform/common/alb/target-group/variables.tf
  terraform/common/backend.tf
  terraform/common/locals.tf
  terraform/common/route53/variables.tf
  terraform/dev/backend.tf
  terraform/dev/ec2/main.tf
  terraform/dev/ecs/locals.tf
  terraform/dev/locals.tf
  terraform/dev/main.tf
  terraform/dev/terraform.tfvars
  terraform/prod/.terraform.lock.hcl
  terraform/prod/backend.tf
  terraform/prod/ecs/locals.tf
  terraform/prod/locals.tf
  terraform/prod/terraform.tfvars
Labels: ci
